In [1]:
1+1

2

# 介绍Markdown

#### 介绍标签

Numpy约定导入方式

In [1]:
import numpy as np

##建立Ndarray多维数组,可以直接使用嵌套列表

In [13]:
arr=np.array(
    [
        [1,2,3,4],
        [2,3,4,5]
    ]
)

维度数量

In [14]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [15]:
arr.ndim

2

In [16]:
arr.shape

(2L, 4L)

数组的数据类型

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr.size

8

In [20]:
np.array(
    [
        ['1','2','3','4']
    ]
)

array([['1', '2', '3', '4']],
      dtype='|S1')

In [25]:
arr2=np.array(['Python','cctv','ibeifeng','hello world'],dtype='|S4')

In [26]:
arr2

array(['Pyth', 'cctv', 'ibei', 'hell'],
      dtype='|S4')

In [31]:
np.array(['1','2','3','4'],dtype='int')

array([1, 2, 3, 4])

数组中元素个数

In [32]:
arr.size

8

In [45]:
arr1=np.array(
    [
        [
            [1,2,3,4,5],
            [2,3,4,5,6],
            [3,7,4,5,6],
            [3,1,4,3,5]
        ],
        [
            [1,222,3,4,5],
            [2,3,4,5,6],
            [3,327,4,5,6],
            [3,1,4,3,53]       
        ]
    ]
)

In [46]:
arr1

array([[[  1,   2,   3,   4,   5],
        [  2,   3,   4,   5,   6],
        [  3,   7,   4,   5,   6],
        [  3,   1,   4,   3,   5]],

       [[  1, 222,   3,   4,   5],
        [  2,   3,   4,   5,   6],
        [  3, 327,   4,   5,   6],
        [  3,   1,   4,   3,  53]]])

In [47]:
arr1.shape

(2L, 4L, 5L)

In [48]:
arr1.dtype

dtype('int32')

In [49]:
arr1.size

40

In [50]:
arr1[0][1][1]

3

In [51]:
np.random.random_simple((2,3))

AttributeError: 'module' object has no attribute 'random_simple'

In [52]:
arr3=np.arange(2,10,2)

In [53]:
arr3

array([2, 4, 6, 8])

In [54]:
arr3.dtype

dtype('int32')

In [59]:
arr3=arr.astype('float')

In [60]:
arr3

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.]])

In [61]:
arr3.dtype

dtype('float64')

In [64]:
arr4=arr.astype('|U2') #使用unicode编码，每个元素长度为2

In [65]:
arr4

array([[u'1', u'2', u'3', u'4'],
       [u'2', u'3', u'4', u'5']],
      dtype='<U2')

In [66]:
arr5=arr.astype('|S2') #使用string编码（转换为十六进制编码），每个元素长度为2

In [67]:
arr5

array([['1', '2', '3', '4'],
       ['2', '3', '4', '5']],
      dtype='|S2')

In [68]:
arr6=np.array([1,2,3,'4'],dtype='float')

In [69]:
arr6

array([ 1.,  2.,  3.,  4.])

In [75]:
arr6.dtype

dtype('float64')

In [72]:
arr6=np.array([1,2,3,'4'],dtype=np.float)

In [73]:
arr6

array([ 1.,  2.,  3.,  4.])

In [76]:
arr6.dtype

dtype('float64')

改变array形状

reshape

In [79]:
arr=np.arange(20)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
arr.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

形状是可变的，但是元素总数是不可变的

In [83]:
a=np.arange(0,20,2)

In [84]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [85]:
a.size

10

In [86]:
a.reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [87]:
a.reshape((-1,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [88]:
b=a.reshape(2,-1)

In [89]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [90]:
b.shape

(2L, 5L)

In [91]:
b.shape=5,-1

In [92]:
b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

#### Numpy算术运算

加法

In [93]:
arr=np.arange(0,20,2)

In [94]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
arr+2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [96]:
arr2=np.arange(2,40,4)   #保证形状是一样的

In [97]:
arr2+arr

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56])

In [98]:
arr2

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38])

In [99]:
arr*arr2

array([  0,  12,  40,  84, 144, 220, 312, 420, 544, 684])

In [100]:
arr/arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
arr2/arr

C:\Users\syph\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 3, 2, 2, 2, 2, 2, 2, 2, 2])

In [105]:
from __future__ import division   #保证数据合法性

In [108]:
arr2/arr

C:\Users\syph\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  3.        ,  2.5       ,  2.33333333,  2.25      ,
        2.2       ,  2.16666667,  2.14285714,  2.125     ,  2.11111111])

数组算数运算，必须保证两边的数组的形状一致

In [109]:
arr=np.random.random((2,3))

In [110]:
arr2=np.random.random((3,2))

In [111]:
arr+arr2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [112]:
arr+arr2.reshape((2,3))

array([[ 0.63039157,  0.86158551,  0.51027763],
       [ 1.38554797,  0.51251079,  0.84433161]])

In [113]:
arr.shape

(2L, 3L)

In [114]:
arr2.shape

(3L, 2L)

In [115]:
arr.dot(arr2)

array([[ 0.38289128,  0.33610864],
       [ 0.50353813,  0.41985108]])

In [116]:
arr

array([[ 0.23597588,  0.58943794,  0.05958609],
       [ 0.99384607,  0.10697989,  0.15617726]])

In [117]:
arr2

array([[ 0.3944157 ,  0.27214756],
       [ 0.45069154,  0.3917019 ],
       [ 0.40553089,  0.68815435]])

第一个矩阵的列轴数值要等于第二个矩阵的行轴数值

In [118]:
new_arr1=np.array([
    [89,95,83],
    [79,75,77],
    [74,51,88]
]
)

In [119]:
new_arr2=np.array([
    [10,1],
    [6,10],
    [9,1]
])

In [120]:
new_arr1.dot(new_arr2)

array([[2207, 1122],
       [1933,  906],
       [1838,  672]])

In [121]:
new_arr1[1][1]

75

In [122]:
new_arr1[1,1]

75

In [123]:
new_arr1[1]

array([79, 75, 77])

In [124]:
new_arr1[1,0:]

array([79, 75, 77])

In [125]:
new_arr1[1,0:2]

array([79, 75])

In [126]:
new_arr1[1][0:2]

array([79, 75])

In [127]:
arr3=np.empty((2,3,4))

In [128]:
arr3

array([[[  2.58405779e-316,   5.82686636e-316,   2.57586342e-316,
           5.82741813e-316],
        [  2.81694255e-316,   5.82683315e-316,   2.57586342e-316,
           5.82652090e-316],
        [  2.81694255e-316,   5.82690904e-316,   2.57586342e-316,
           5.82740864e-316]],

       [[  2.81694255e-316,   5.82696833e-316,   2.57586342e-316,
           5.67585578e-316],
        [  2.81694255e-316,   5.82689481e-316,   2.57586342e-316,
           5.82727584e-316],
        [  2.81694255e-316,   5.67596053e-316,   2.57586342e-316,
           5.70870403e-316]]])

In [129]:
arr3=np.random.random(2,3,4)

TypeError: random_sample() takes at most 1 positional argument (3 given)

In [130]:
arr3=np.random.random((2,3,4))

In [131]:
arr3

array([[[ 0.45679645,  0.45774646,  0.66620283,  0.75168583],
        [ 0.34429717,  0.38059929,  0.13615264,  0.60130514],
        [ 0.91281745,  0.63328332,  0.26374673,  0.86851959]],

       [[ 0.3835629 ,  0.3844736 ,  0.7811334 ,  0.02670579],
        [ 0.38952024,  0.82273642,  0.3002022 ,  0.55788252],
        [ 0.1060339 ,  0.52140039,  0.6689426 ,  0.45901606]]])

In [132]:
arr3[0][1:2]

array([[ 0.34429717,  0.38059929,  0.13615264,  0.60130514]])

In [133]:
arr3[0][1:]

array([[ 0.34429717,  0.38059929,  0.13615264,  0.60130514],
       [ 0.91281745,  0.63328332,  0.26374673,  0.86851959]])

In [134]:
arr3[0,1:]

array([[ 0.34429717,  0.38059929,  0.13615264,  0.60130514],
       [ 0.91281745,  0.63328332,  0.26374673,  0.86851959]])

In [135]:
arr3[0,[0,2]:]

TypeError: slice indices must be integers or None or have an __index__ method

In [136]:
arr3[0,[0,2]]

array([[ 0.45679645,  0.45774646,  0.66620283,  0.75168583],
       [ 0.91281745,  0.63328332,  0.26374673,  0.86851959]])

In [137]:
arr3[0,[[0:2],2]]

SyntaxError: invalid syntax (<ipython-input-137-a96108aec7ce>, line 1)

In [138]:
arr3[0,[0,2],1:]

array([[ 0.45774646,  0.66620283,  0.75168583],
       [ 0.63328332,  0.26374673,  0.86851959]])

In [139]:
arr3

array([[[ 0.45679645,  0.45774646,  0.66620283,  0.75168583],
        [ 0.34429717,  0.38059929,  0.13615264,  0.60130514],
        [ 0.91281745,  0.63328332,  0.26374673,  0.86851959]],

       [[ 0.3835629 ,  0.3844736 ,  0.7811334 ,  0.02670579],
        [ 0.38952024,  0.82273642,  0.3002022 ,  0.55788252],
        [ 0.1060339 ,  0.52140039,  0.6689426 ,  0.45901606]]])

In [141]:
arr3[0][0,2][1:3]

IndexError: invalid index to scalar variable.

In [142]:
arr3[0,0:2,1:3]    #切片是一个视图

array([[ 0.45774646,  0.66620283],
       [ 0.38059929,  0.13615264]])

In [143]:
arr3[0][0:2][1:3]   #视图

array([[ 0.34429717,  0.38059929,  0.13615264,  0.60130514]])

In [144]:
arr3[0][0:2][1][1:3]

array([ 0.38059929,  0.13615264])

In [145]:
arr3[0,0:2,1:3]

array([[ 0.45774646,  0.66620283],
       [ 0.38059929,  0.13615264]])

布尔型索引（筛选的作用

In [146]:
arr3>0.5

array([[[False, False,  True,  True],
        [False, False, False,  True],
        [ True,  True, False,  True]],

       [[False, False,  True, False],
        [False,  True, False,  True],
        [False,  True,  True, False]]], dtype=bool)

In [152]:
arr3[arr3>0.5]

array([ 0.66620283,  0.75168583,  0.60130514,  0.91281745,  0.63328332,
        0.86851959,  0.7811334 ,  0.82273642,  0.55788252,  0.52140039,
        0.6689426 ])

花式索引，利用整数数组进行索引

In [147]:
arr=np.arange(32).reshape((8,4))

In [148]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [149]:
arr[[0,3,5]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [151]:
arr[[0,3,5],[0,3,2]]    #前一个【】取出行，后一个【】取出对应的列。即先取出3行，再在这三行找对应的位置上的值

array([ 0, 15, 22])

In [153]:
arr4=np.array([
    'Tom','Alice','Python'
])

In [154]:
arr4[arr4=='Tom']=1

In [155]:
arr4

array(['1', 'Alice', 'Python'],
      dtype='|S6')

In [156]:
arr4=np.array([
    'Tom','Alice','Python',np.nan
])

In [161]:
arr5

array([['1', '2', '3', '4'],
       ['2', '3', '4', '5']],
      dtype='|S2')

In [162]:
arr5[arr5=='nan']='1'

In [163]:
arr5

array([['1', '2', '3', '4'],
       ['2', '3', '4', '5']],
      dtype='|S2')

In [164]:
arr6=np.arange(32).reshape((4,8))

In [165]:
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [166]:
arr6.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [167]:
np.ix_([0,3,5],[0,2,3])

(array([[0],
        [3],
        [5]]), array([[0, 2, 3]]))

In [168]:
arr6[np.ix_([0,3,5],[0,2,4])]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [169]:
arr6[np.ix_([0,3,5],[0,2,3])]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [170]:
arr6[np.ix_([0,3,5],[0,2,1,3])]    #生成一个索引器

IndexError: index 5 is out of bounds for axis 0 with size 4

In [171]:
arr6(np.ix_([0,3,5],[0,2,3]))

TypeError: 'numpy.ndarray' object is not callable

In [172]:
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [173]:
arr6=arr6.reshape((8,4))

In [174]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [175]:
arr6[np.ix_([0,3,5],[0,2,3])]

array([[ 0,  2,  3],
       [12, 14, 15],
       [20, 22, 23]])

In [176]:
arr7=arr6.T   #数组的T属性，视图

In [177]:
arr7

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [178]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [185]:
arr8=arr6.transpose()  #转置函数，视图

In [181]:
arr8

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [182]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [183]:
arr8[0][0]=0

In [184]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [4]:
import numpy as np

In [5]:
arr=np.random.random((3,4,5))

In [6]:
arr

array([[[ 0.8125278 ,  0.76448278,  0.08823121,  0.04887398,  0.64215601],
        [ 0.46071389,  0.75020606,  0.13123765,  0.68531213,  0.54835976],
        [ 0.81073871,  0.15841416,  0.48942166,  0.08582957,  0.85688816],
        [ 0.93911294,  0.71377543,  0.25887612,  0.67487568,  0.0569406 ]],

       [[ 0.42798776,  0.64526025,  0.69283503,  0.40310821,  0.26931645],
        [ 0.96614805,  0.88905183,  0.08901272,  0.29471058,  0.48628287],
        [ 0.10184039,  0.81492698,  0.57800663,  0.50669401,  0.94904584],
        [ 0.87436505,  0.27168302,  0.78319204,  0.08594362,  0.10385564]],

       [[ 0.719367  ,  0.11366216,  0.4821142 ,  0.34880088,  0.31962394],
        [ 0.19641393,  0.63998156,  0.56355   ,  0.63046464,  0.4826888 ],
        [ 0.55080387,  0.96260706,  0.94348104,  0.37195059,  0.5257234 ],
        [ 0.16901596,  0.07022067,  0.48792924,  0.75789585,  0.34336484]]])

In [7]:
np.abs(arr)

array([[[ 0.8125278 ,  0.76448278,  0.08823121,  0.04887398,  0.64215601],
        [ 0.46071389,  0.75020606,  0.13123765,  0.68531213,  0.54835976],
        [ 0.81073871,  0.15841416,  0.48942166,  0.08582957,  0.85688816],
        [ 0.93911294,  0.71377543,  0.25887612,  0.67487568,  0.0569406 ]],

       [[ 0.42798776,  0.64526025,  0.69283503,  0.40310821,  0.26931645],
        [ 0.96614805,  0.88905183,  0.08901272,  0.29471058,  0.48628287],
        [ 0.10184039,  0.81492698,  0.57800663,  0.50669401,  0.94904584],
        [ 0.87436505,  0.27168302,  0.78319204,  0.08594362,  0.10385564]],

       [[ 0.719367  ,  0.11366216,  0.4821142 ,  0.34880088,  0.31962394],
        [ 0.19641393,  0.63998156,  0.56355   ,  0.63046464,  0.4826888 ],
        [ 0.55080387,  0.96260706,  0.94348104,  0.37195059,  0.5257234 ],
        [ 0.16901596,  0.07022067,  0.48792924,  0.75789585,  0.34336484]]])

In [8]:
np.sqrt(arr)

array([[[ 0.90140324,  0.87434706,  0.29703739,  0.22107461,  0.80134638],
        [ 0.67875908,  0.86614437,  0.36226737,  0.82783581,  0.74051317],
        [ 0.9004103 ,  0.39801277,  0.69958678,  0.29296684,  0.92568254],
        [ 0.9690784 ,  0.84485231,  0.50879871,  0.82150817,  0.23862229]],

       [[ 0.65420773,  0.80328093,  0.83236712,  0.63490803,  0.51895708],
        [ 0.9829283 ,  0.94289545,  0.29834999,  0.54287253,  0.69733986],
        [ 0.31912442,  0.90273306,  0.76026747,  0.71182442,  0.97418984],
        [ 0.93507489,  0.52123222,  0.88498138,  0.29316142,  0.3222664 ]],

       [[ 0.84815506,  0.3371382 ,  0.69434444,  0.59059367,  0.56535293],
        [ 0.44318611,  0.79998848,  0.75069967,  0.79401804,  0.69475809],
        [ 0.74216162,  0.98112541,  0.97132952,  0.60987752,  0.72506786],
        [ 0.4111155 ,  0.26499183,  0.69851932,  0.87057214,  0.58597341]]])

In [9]:
help(np.log)

Help on ufunc object:

log = class ufunc(__builtin__.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arra

In [11]:
arr=arange(32).reshape((2,-1))

NameError: name 'arange' is not defined

In [12]:
arr=np.arange(32).reshape((2,-1))

In [13]:
arr2=np.arange(32).reshape((2,-1))

In [14]:
np.power(arr,arr2)

array([[          1,           1,           4,          27,         256,
               3125,       46656,      823543,    16777216,   387420489,
         1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
         1500973039],
       [          0,  1681328401,   457441280,  -306639989,           0,
          878082373,   977272832, -1276351769,           0,  1296002393,
          603979776,  -714244925,           0, -1266004979,  1073741824,
        -2010103841]])

In [15]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [16]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [17]:
arr=np.arange(10).reshape((2,-1))

In [18]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arr2=np.arange(10).reshape((2,-1))

In [20]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
np.power(arr,arr2)   #按位做power  x的y次方

array([[        1,         1,         4,        27,       256],
       [     3125,     46656,    823543,  16777216, 387420489]])

In [22]:
arr3=np.empty((10,10,10))

In [23]:
np.isnan(arr3)   #判断是否有空值

array([[[False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False]],

       [[False, False, False, False, False, False, False, False, False,
         False],
        [False, Fal

In [26]:
arr3[1,1]=np.NaN

In [27]:
np.isnan(arr3)

array([[[False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         False]],

       [[False, False, False, False, False, False, False, False, False,
         False],
        [ True,  Tr

In [30]:
arr4=arr3.astype('|U20')

In [32]:
arr4=np.empty((2,3)).astype('|U20')

In [33]:
arr4

array([[u'0.0', u'0.0', u'0.0'],
       [u'0.0', u'0.0', u'0.0']],
      dtype='<U20')

In [34]:
arr4=np.array([
    [np.NaN,1,2,3],
    [2,3,4,5]
])

In [35]:
np.isnan(arr4)   #判断数组是否具备空值，空值返回true

array([[ True, False, False, False],
       [False, False, False, False]], dtype=bool)

In [36]:
arr4

array([[ nan,   1.,   2.,   3.],
       [  2.,   3.,   4.,   5.]])

In [37]:
arr4=np.random.random((2,3,4))

In [38]:
arr5=np.random.random((2,3,4))

In [39]:
np.add(arr4,arr5)  #等同于arr4+arr5

array([[[ 1.50940656,  1.68282988,  0.6712057 ,  0.91729981],
        [ 1.12708667,  0.90096175,  0.82115411,  0.96836737],
        [ 1.04965006,  0.33894754,  0.16831356,  1.04433315]],

       [[ 0.40956307,  1.95728398,  1.14499565,  1.35285576],
        [ 0.33446929,  0.42510349,  1.45647596,  1.06211608],
        [ 1.15386202,  1.85427736,  0.31076855,  1.02043164]]])

In [40]:
arr=np.array([1.0,2.0,3.0,4.0])

In [41]:
arr.max()

4.0

In [42]:
arr.min()

1.0

In [43]:
arr.mean()

2.5

In [44]:
arr.std()

1.1180339887498949

In [48]:
np.sqrt(np.power(arr - arr.mean(),2).sum()/arr.size())

TypeError: 'int' object is not callable

In [52]:
np.power(arr - arr.mean(),2).sum()/arr.size()

TypeError: 'int' object is not callable

In [53]:
arr

array([ 1.,  2.,  3.,  4.])

# np.where函数

In [54]:
1 if 2>3 else 0   #三元表达式

0

满足True则显示第一个数组的对应位置的元素，否则显示第二个对应位置的元素

In [55]:
xarr=np.array([1.1,2.2,3.3,4.4])

In [56]:
yarr=np.array([1.2,2.3,3.4,4.5])

In [57]:
bool_arr=np.array([True,False,False,True])

In [61]:
zip_arr=zip(xarr,yarr,bool_arr)   #数组合并

In [70]:
result=['%.1f'%x if bl else '%.1f'%y for x,y,bl in zip_arr]

In [71]:
result

['1.1', '2.3', '3.4', '4.4']

In [67]:
zip_arr

[(1.1000000000000001, 1.2, True),
 (2.2000000000000002, 2.2999999999999998, False),
 (3.2999999999999998, 3.3999999999999999, False),
 (4.4000000000000004, 4.5, True)]

In [76]:
result=[(x if bl else y for x,y,bl in zip_arr) if x>2 else 1] 

In [79]:
result1=[(x if bl else y) for x,y,bl in zip_arr if x>2]

In [82]:
result

[2.2999999999999998, 3.3999999999999999, 4.4000000000000004]

In [81]:
result1

[2.2999999999999998, 3.3999999999999999, 4.4000000000000004]

### np.where(表达式数组，当前表达式为True提取数据的数组，当前表达式为false提取数据的数组)

In [83]:
np.where(bool_arr,xarr,yarr)

array([ 1.1,  2.3,  3.4,  4.4])

#### np.unique 求数组的非重复值

In [88]:
arr=np.array(['中国','美国','英国','印度','毛里求斯','梵蒂冈','毛里求斯','梵蒂冈','中国','中国'])

In [89]:
arr

array(['\xe4\xb8\xad\xe5\x9b\xbd', '\xe7\xbe\x8e\xe5\x9b\xbd',
       '\xe8\x8b\xb1\xe5\x9b\xbd', '\xe5\x8d\xb0\xe5\xba\xa6',
       '\xe6\xaf\x9b\xe9\x87\x8c\xe6\xb1\x82\xe6\x96\xaf',
       '\xe6\xa2\xb5\xe8\x92\x82\xe5\x86\x88',
       '\xe6\xaf\x9b\xe9\x87\x8c\xe6\xb1\x82\xe6\x96\xaf',
       '\xe6\xa2\xb5\xe8\x92\x82\xe5\x86\x88', '\xe4\xb8\xad\xe5\x9b\xbd',
       '\xe4\xb8\xad\xe5\x9b\xbd'],
      dtype='|S12')

In [90]:
for i in arr:
    print i

中国
美国
英国
印度
毛里求斯
梵蒂冈
毛里求斯
梵蒂冈
中国
中国


In [91]:
arr1=np.unique(arr)   #取出唯一值

In [92]:
for i in arr1:
    print i

中国
印度
梵蒂冈
毛里求斯
美国
英国


### 数组数据据文件读写

#### 数组以二进制形式读写

1.save  写数据

In [94]:
arr=np.random.random((2,3,4))

In [96]:
help(np.save)

Help on function save in module numpy.lib.npyio:

save(file, arr, allow_pickle=True, fix_imports=True)
    Save an array to a binary file in NumPy ``.npy`` format.
    
    Parameters
    ----------
    file : file, str, or pathlib.Path
        File or filename to which the data is saved.  If file is a file-object,
        then the filename is unchanged.  If file is a string or Path, a ``.npy``
        extension will be appended to the file name if it does not already
        have one.
    allow_pickle : bool, optional
        Allow saving object arrays using Python pickles. Reasons for disallowing
        pickles include security (loading pickled data can execute arbitrary
        code) and portability (pickled objects may not be loadable on different
        Python installations, for example if the stored objects require libraries
        that are not available, and not all pickled data is compatible between
        Python 2 and Python 3).
        Default: True
    fix_imports : bool

In [98]:
np.save('data',arr)   #将多维数组存储到文件，自动添加后缀.npy(二进制文件)

In [101]:
arr

array([[[ 0.94588137,  0.78603508,  0.70958794,  0.71266207],
        [ 0.25254062,  0.76298767,  0.84475678,  0.23482786],
        [ 0.66569846,  0.09543246,  0.99147911,  0.468672  ]],

       [[ 0.5930699 ,  0.84114751,  0.01143617,  0.14667971],
        [ 0.58366112,  0.73864042,  0.12633762,  0.36491579],
        [ 0.269187  ,  0.12177017,  0.52325194,  0.76108179]]])

#### 2.读取二进制形式的数据文件

In [99]:
arr2=np.load('data.npy')   #读取数据的时候，我们需要设置文件后缀

In [100]:
arr2

array([[[ 0.94588137,  0.78603508,  0.70958794,  0.71266207],
        [ 0.25254062,  0.76298767,  0.84475678,  0.23482786],
        [ 0.66569846,  0.09543246,  0.99147911,  0.468672  ]],

       [[ 0.5930699 ,  0.84114751,  0.01143617,  0.14667971],
        [ 0.58366112,  0.73864042,  0.12633762,  0.36491579],
        [ 0.269187  ,  0.12177017,  0.52325194,  0.76108179]]])

### 存取文本文件

#### 1.读取数据

In [105]:
help(np.loadtxt)
#fname  文件名
#dtype  数据类型
#comment 注释行的符号定义
#delimiter 数据分隔符的定义
#converteres 转换函数
#usecols  使用哪些列

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence, optional
        The characters or list of

In [108]:
arr4=np.loadtxt('example.csv',delimiter=',')

In [109]:
arr4

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 3.,  4.,  5.,  6.]])

In [111]:
from io import StringIO

In [112]:
c=StringIO(u'0 1\n2 3')

In [113]:
c

In [114]:
np.loadtxt(c)

array([[ 0.,  1.],
       [ 2.,  3.]])

In [115]:
np.genfromtxt('example.csv',delimiter=',')    #类似于loadtxt

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 3.,  4.,  5.,  6.]])

#### 数据写入文本文件

In [117]:
np.savetxt('arr.csv',arr4,delimiter=',')

In [123]:
np.savetxt('arr.csv',arr4.reshape((2,6)),delimiter=',',fmt='%.2f')  #fmt格式化文本

In [124]:
arr3=np.random.random((2,3,4))

In [125]:
arr3

array([[[ 0.68410928,  0.95239915,  0.20632003,  0.41063736],
        [ 0.99244575,  0.27865451,  0.43363976,  0.63250732],
        [ 0.66609992,  0.54662307,  0.98680682,  0.62131106]],

       [[ 0.44802524,  0.1823203 ,  0.47962814,  0.22129827],
        [ 0.34071447,  0.89021916,  0.42463782,  0.78157073],
        [ 0.47700681,  0.31315309,  0.7880888 ,  0.49292734]]])

### 如果数组为二维以上的数组，则必须转换为二维数组才能进行存储，否则一定会出错

In [129]:
np.savetxt('arr1.csv',arr3.reshape((4,6)),delimiter=',',fmt='%.2f')